### ISSUE TITLE
qr code

### ISSUE THREAD

**Issue by info-lamin** [cyberboysumanjay/upayi#1]
if amount is entered in optional field, the amount in the pay link will not be editable
but you didn't mention the amount in the QR code so though the person had entered a amount if he scans the QR code there will be no prefixed amount

**Comment by cyberboysumanjay** [comment]
Hey @Info-lamin  
Thanks for pointing this, if I understood your query correctly it should be fixed with this https://github.com/cyberboysumanjay/upayi/commit/a359aa8047036ff7ab17f106bc58e6e14031eaf3 commit.

Let me know if it is working fine for you or not 😃 
Closing this issue for now
